#!/bin/bash

for file in src/*/*.c
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/42sh/msh/g" "$file"
done

for file in includes/*.h
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/42sh/msh/g" "$file"
done

for file in Makefile
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/42sh/minishell/g" "$file"
done

for file in libft/Makefile
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/42sh/minishell/g" "$file"
done

for file in libft/src/*/*.c
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/42sh/msh/g" "$file"
done

for file in src/*/*.c
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/21sh/msh/g" "$file"
done

for file in includes/*.h
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/21sh/msh/g" "$file"
done

for file in Makefile
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/21sh/minishell/g" "$file"
done

for file in libft/Makefile
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/21sh/minishell/g" "$file"
done

for file in libft/src/*/*.c
do
	echo "Traitement de $file ..."
	sed -i '' -e "s/21sh/msh/g" "$file"
done
